"""Changed naming of column name in addresses table

Revision ID: 09e5b94b4f02
Revises: 6be013d6fdb9
Create Date: 2020-05-07 11:40:01.376723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e5b94b4f02'
down_revision = '6be013d6fdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('AddressLine1', sa.String(), nullable=True))
    op.drop_column('addresses', 'line_1')
    op.alter_column('companies', 'incorporated',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'incorporated',
               existing_type=sa.DATE(),
               nullable=False)
    op.add_column('addresses', sa.Column('line_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'AddressLine1')
    # ### end Alembic commands ###
