"""test for changes

Revision ID: 1a0f6b18da5d
Revises: 3055b1b769b2
Create Date: 2020-05-07 12:22:46.196818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0f6b18da5d'
down_revision = '3055b1b769b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
