"""test

Revision ID: 822107eec3d6
Revises: 7dae4ff5cf0e
Create Date: 2020-05-07 12:32:13.599785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822107eec3d6'
down_revision = '7dae4ff5cf0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
