"""test

Revision ID: 85acf40e0e7b
Revises: 8267854525ca
Create Date: 2020-05-08 07:17:44.799326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85acf40e0e7b'
down_revision = '8267854525ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('line_1', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('line_2', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('line_3', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('occupier_id', sa.Integer(), nullable=True))
    op.add_column('addresses', sa.Column('po_box', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('post_town', sa.String(), nullable=True))
    op.create_foreign_key(None, 'addresses', 'companies', ['occupier_id'], ['number'])
    op.drop_column('addresses', 'POBox')
    op.drop_column('addresses', 'addressLine1')
    op.drop_column('addresses', 'addressLine2')
    op.drop_column('addresses', 'postTown')
    op.drop_column('addresses', 'addressLine3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('addressLine3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('postTown', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('addressLine2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('addressLine1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('POBox', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'post_town')
    op.drop_column('addresses', 'po_box')
    op.drop_column('addresses', 'occupier_id')
    op.drop_column('addresses', 'line_3')
    op.drop_column('addresses', 'line_2')
    op.drop_column('addresses', 'line_1')
    # ### end Alembic commands ###
