"""datetime test

Revision ID: 46aac06cfaf5
Revises: 822107eec3d6
Create Date: 2020-05-07 12:34:43.188699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46aac06cfaf5'
down_revision = '822107eec3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
