"""Various updates for schemas etc.

Revision ID: 7a49bf564169
Revises: 85acf40e0e7b
Create Date: 2020-05-09 08:39:40.514394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a49bf564169'
down_revision = '85acf40e0e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
