"""Added company siccode relation

Revision ID: aa13cc2bbbe3
Revises: 453ce5156068
Create Date: 2020-05-12 17:18:43.271972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa13cc2bbbe3'
down_revision = '453ce5156068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('co_number', sa.Integer(), nullable=True),
    sa.Column('siccode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['co_number'], ['companies.number'], ),
    sa.ForeignKeyConstraint(['siccode'], ['siccodes.code'], )
    )
    op.add_column('siccodes', sa.Column('record_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siccodes', 'record_created')
    op.drop_table('association')
    # ### end Alembic commands ###
