"""Check

Revision ID: de0e09a3fbaa
Revises: 6d950cc2c544
Create Date: 2020-05-11 07:13:28.364762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0e09a3fbaa'
down_revision = '6d950cc2c544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
