"""Readded address table

Revision ID: 6d950cc2c544
Revises: 08ce6038a16d
Create Date: 2020-05-10 20:39:21.830871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d950cc2c544'
down_revision = '08ce6038a16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('record_created', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('address_line3', sa.String(), nullable=True),
    sa.Column('po_box', sa.String(), nullable=True),
    sa.Column('post_town', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('occupier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['occupier_id'], ['companies.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
