"""new

Revision ID: f5a5383d57f5
Revises: 46aac06cfaf5
Create Date: 2020-05-07 13:05:54.502557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a5383d57f5'
down_revision = '46aac06cfaf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'createdAt', new_column_name='created')
    op.execute("UPDATE companies SET created = CAST('2020-05-07 13:10:05 +0000' AS TIMESTAMP) ")
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
