"""Switched primary key direction on companies/addresses

Revision ID: 453ce5156068
Revises: de0e09a3fbaa
Create Date: 2020-05-12 11:02:39.340919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453ce5156068'
down_revision = 'de0e09a3fbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_occupier_id_fkey', 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'occupier_id')
    op.add_column('companies', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'address_id')
    op.add_column('addresses', sa.Column('occupier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('addresses_occupier_id_fkey', 'addresses', 'companies', ['occupier_id'], ['number'])
    # ### end Alembic commands ###
