"""Reset address table

Revision ID: 08ce6038a16d
Revises: cb2adcec2f17
Create Date: 2020-05-10 20:38:54.231988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08ce6038a16d'
down_revision = 'cb2adcec2f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('record_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('occupier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('po_box', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_town', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address_line3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['occupier_id'], ['companies.number'], name='addresses_occupier_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey')
    )
    # ### end Alembic commands ###
