"""Added defaults to User

Revision ID: 7ab2b3b91cdd
Revises: 95e3c60ba70d
Create Date: 2020-05-18 08:14:02.892462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab2b3b91cdd'
down_revision = '95e3c60ba70d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
