"""Updated address atts

Revision ID: cab1cbabbec0
Revises: 7a49bf564169
Create Date: 2020-05-10 11:13:56.431138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab1cbabbec0'
down_revision = '7a49bf564169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('address_line_1', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('address_line_3', sa.String(), nullable=True))
    op.drop_column('addresses', 'line_2')
    op.drop_column('addresses', 'line_1')
    op.drop_column('addresses', 'line_3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('line_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('line_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('line_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'address_line_3')
    op.drop_column('addresses', 'address_line_2')
    op.drop_column('addresses', 'address_line_1')
    # ### end Alembic commands ###
