"""Added relationships

Revision ID: 8267854525ca
Revises: 29496d664875
Create Date: 2020-05-08 07:06:55.603224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8267854525ca'
down_revision = '29496d664875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
