"""Temporarily changed User sub types

Revision ID: d6425195a676
Revises: 7ab2b3b91cdd
Create Date: 2020-05-18 08:57:37.692632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6425195a676'
down_revision = '7ab2b3b91cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
