"""Adjusted snake case on address lines

Revision ID: cb2adcec2f17
Revises: cab1cbabbec0
Create Date: 2020-05-10 20:12:48.749138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2adcec2f17'
down_revision = 'cab1cbabbec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('address_line3', sa.String(), nullable=True))
    op.drop_column('addresses', 'address_line_3')
    op.drop_column('addresses', 'address_line_2')
    op.drop_column('addresses', 'address_line_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('address_line_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('address_line_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('address_line_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'address_line3')
    op.drop_column('addresses', 'address_line2')
    op.drop_column('addresses', 'address_line1')
    # ### end Alembic commands ###
