"""Updated director table

Revision ID: 3055b1b769b2
Revises: c70ac116b8f1
Create Date: 2020-05-07 12:07:40.362050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3055b1b769b2'
down_revision = 'c70ac116b8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('firstNames', sa.String(), nullable=True))
    op.add_column('directors', sa.Column('lastName', sa.String(), nullable=True))
    op.drop_column('directors', 'firstnames')
    op.drop_column('directors', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('directors', sa.Column('firstnames', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('directors', 'lastName')
    op.drop_column('directors', 'firstNames')
    # ### end Alembic commands ###
