"""time stamp

Revision ID: 5fa3444f5d2c
Revises: ef98fbb3406e
Create Date: 2020-05-07 12:26:13.919197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa3444f5d2c'
down_revision = 'ef98fbb3406e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
