"""Test entry

Revision ID: 6b2240ac64a1
Revises: 3835840b901f
Create Date: 2020-05-07 11:22:43.334672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2240ac64a1'
down_revision = '3835840b901f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_1', sa.String(), nullable=True),
    sa.Column('line_2', sa.String(), nullable=True),
    sa.Column('line_3', sa.String(), nullable=True),
    sa.Column('po_box', sa.String(), nullable=True),
    sa.Column('post_town', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstnames', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siccodes',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siccodes')
    op.drop_table('directors')
    op.drop_table('addresses')
    # ### end Alembic commands ###
