"""Changed naming of column name in addresses table

Revision ID: 6d882a784ff0
Revises: 09e5b94b4f02
Create Date: 2020-05-07 11:40:43.941889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d882a784ff0'
down_revision = '09e5b94b4f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('addressLine1', sa.String(), nullable=True))
    op.drop_column('addresses', 'AddressLine1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('AddressLine1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'addressLine1')
    # ### end Alembic commands ###
