"""Changed various column names

Revision ID: 7dc799d04408
Revises: 6d882a784ff0
Create Date: 2020-05-07 12:05:19.782316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc799d04408'
down_revision = '6d882a784ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
