"""Changed naming of column name in addresses table

Revision ID: c70ac116b8f1
Revises: 7dc799d04408
Create Date: 2020-05-07 12:05:52.986751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70ac116b8f1'
down_revision = '7dc799d04408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('POBox', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('addressLine2', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('addressLine3', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('postTown', sa.String(), nullable=True))
    op.drop_column('addresses', 'line_2')
    op.drop_column('addresses', 'po_box')
    op.drop_column('addresses', 'line_3')
    op.drop_column('addresses', 'post_town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('post_town', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('line_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('po_box', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('addresses', sa.Column('line_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('addresses', 'postTown')
    op.drop_column('addresses', 'addressLine3')
    op.drop_column('addresses', 'addressLine2')
    op.drop_column('addresses', 'POBox')
    # ### end Alembic commands ###
