"""test for changes

Revision ID: ef98fbb3406e
Revises: 1a0f6b18da5d
Create Date: 2020-05-07 12:23:37.408962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef98fbb3406e'
down_revision = '1a0f6b18da5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
